import csv
import json
import math
import os
import re
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


CSV_FIELDS = [
    "timestamp_ns",
    "image_front",
    "image_left",
    "image_right",
    "image_rear",
    "motor_angle",
    "motor_speed",
    "mission_label",
    "lap_index",
    "source_mode",
    "scan_path",
    "imu_orientation_x",
    "imu_orientation_y",
    "imu_orientation_z",
    "imu_orientation_w",
    "imu_angular_velocity_x",
    "imu_angular_velocity_y",
    "imu_angular_velocity_z",
    "imu_linear_acceleration_x",
    "imu_linear_acceleration_y",
    "imu_linear_acceleration_z",
    "odom_position_x",
    "odom_position_y",
    "odom_position_z",
    "odom_orientation_x",
    "odom_orientation_y",
    "odom_orientation_z",
    "odom_orientation_w",
    "odom_linear_x",
    "odom_angular_z",
    "notes",
]


def expand_path(path: str) -> Path:
    return Path(os.path.expandvars(os.path.expanduser(path))).resolve()


def sanitize_session_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_.-]+", "_", name.strip())
    return cleaned.strip("._-") or "session"


def make_session_dir(base_dir: str, session_name: str, now: Optional[datetime] = None) -> Path:
    timestamp = (now or datetime.now()).strftime("%Y%m%d_%H%M%S")
    session = f"{timestamp}_{sanitize_session_name(session_name)}"
    session_dir = expand_path(base_dir) / session
    for relative in [
        "images/front",
        "images/left",
        "images/right",
        "images/rear",
        "scan",
        "debug",
    ]:
        (session_dir / relative).mkdir(parents=True, exist_ok=True)
    return session_dir


def atomic_write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=str(path.parent), delete=False
    ) as tmp:
        json.dump(data, tmp, indent=2, ensure_ascii=False, sort_keys=True)
        tmp.write("\n")
        tmp_name = tmp.name
    os.replace(tmp_name, path)


def open_samples_csv(path: Path) -> Tuple[Any, csv.DictWriter]:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = path.open("w", newline="", encoding="utf-8")
    writer = csv.DictWriter(handle, fieldnames=CSV_FIELDS)
    writer.writeheader()
    return handle, writer


def relative_to_session(session_dir: Path, path: Optional[Path]) -> str:
    if path is None:
        return ""
    try:
        return str(path.relative_to(session_dir)).replace("\\", "/")
    except ValueError:
        return str(path)


def stamp_to_ns(msg: Any, fallback_ns: Optional[int] = None) -> int:
    header = getattr(msg, "header", None)
    stamp = getattr(header, "stamp", None)
    sec = getattr(stamp, "sec", None)
    nanosec = getattr(stamp, "nanosec", None)
    if sec is not None and nanosec is not None and (sec != 0 or nanosec != 0):
        return int(sec) * 1_000_000_000 + int(nanosec)
    if fallback_ns is not None:
        return int(fallback_ns)
    return int(datetime.now().timestamp() * 1_000_000_000)


def ros_time_to_ns(clock_now: Any) -> int:
    return int(clock_now.nanoseconds)


def motor_from_msg(msg: Any) -> Tuple[float, float]:
    if hasattr(msg, "angle") and hasattr(msg, "speed"):
        return float(msg.angle), float(msg.speed)
    data = getattr(msg, "data", None)
    if data is not None and len(data) >= 2:
        return float(data[0]), float(data[1])
    raise ValueError(f"unsupported motor message type: {type(msg)!r}")


def string_from_msg(msg: Any, default: str = "idle") -> str:
    value = getattr(msg, "data", None)
    if value is None:
        return default
    return str(value) or default


def image_suffix(image_format: str) -> str:
    fmt = image_format.lower().strip(".")
    if fmt not in {"jpg", "jpeg", "png"}:
        raise ValueError("image_format must be jpg or png")
    return "jpg" if fmt == "jpeg" else fmt


def numeric_stats(values: Sequence[float]) -> Dict[str, Optional[float]]:
    cleaned = [float(v) for v in values if v is not None and math.isfinite(float(v))]
    if not cleaned:
        return {"min": None, "max": None, "mean": None, "std": None}
    mean = sum(cleaned) / len(cleaned)
    variance = sum((value - mean) ** 2 for value in cleaned) / len(cleaned)
    return {
        "min": min(cleaned),
        "max": max(cleaned),
        "mean": mean,
        "std": math.sqrt(variance),
    }


def write_session_readme(session_dir: Path, session_name: str, topics: Dict[str, str]) -> None:
    lines = [
        f"# IL data session: {session_name}",
        "",
        "This directory was generated by `il_data_tools`.",
        "",
        "## Topics",
    ]
    for key, value in sorted(topics.items()):
        lines.append(f"- {key}: `{value}`")
    lines.extend(
        [
            "",
            "## Safety Note",
            "",
            "This recorder only subscribes to vehicle topics. It does not publish `/xycar_motor`.",
        ]
    )
    (session_dir / "README_session.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def label_counts(rows: Iterable[Dict[str, str]]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for row in rows:
        label = row.get("mission_label") or "unknown"
        counts[label] = counts.get(label, 0) + 1
    return counts
