frame_id: map
closed: false
reverse_ranges:
- 9-13
- 21-25
waypoints:
- name: WP_00
  x: 1.6831
  y: 0.8636
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_01
  x: 0.9197
  y: 1.0013
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_02
  x: 0.6319
  y: 1.552
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_03
  x: 0.7946
  y: 2.1777
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_04
  x: 0.9448
  y: 2.8411
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_05
  x: 0.9072
  y: 3.6046
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_06
  x: 0.8447
  y: 4.2554
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_07
  x: 0.9453
  y: 4.7031
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_08
  x: 1.3008
  y: 4.8647
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_09
  x: 1.5432
  y: 4.9779
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_10
  x: 1.2523
  y: 4.9132
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_11
  x: 0.7514
  y: 4.6223
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_12
  x: 0.4121
  y: 4.493
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_13
  x: 0.35
  y: 4.44
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_14
  x: -0.0889
  y: 4.1859
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_15
  x: 0.6221
  y: 4.59
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_16
  x: 2.1117
  y: 4.921
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_17
  x: 2.8227
  y: 4.3948
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_18
  x: 2.7843
  y: 3.7426
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_19
  x: 2.7092
  y: 3.1167
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_20
  x: 2.7342
  y: 2.541
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_21
  x: 3.0095
  y: 1.9777
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_22
  x: 2.6216
  y: 2.2906
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_23
  x: 2.2086
  y: 2.7162
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_24
  x: 2.0585
  y: 3.2169
  controller_to_next: global_path
  travel_direction_to_next: reverse
- name: WP_25
  x: 2.0084
  y: 3.4176
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_26
  x: 2.0835
  y: 3.1293
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_27
  x: 2.5964
  y: 2.4909
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_28
  x: 2.997
  y: 2.0027
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_29
  x: 2.7467
  y: 1.4269
  controller_to_next: global_path
  travel_direction_to_next: forward
- name: WP_30
  x: 1.8708
  y: 0.8512
  controller_to_next: global_path
  travel_direction_to_next: forward
