description: 'safe alias of measured extrinsic (2026-07-12)'
lidar_frame: laser_frame
camera_frame: wide_camera_optical_frame
camera_position_in_laser_frame_m:
  x_forward: -0.105
  y_left: 0.0
  z_up: 0.09
correction_rotation_deg_in_camera_optical:
  roll: 9.0
  pitch: 0.0
  yaw: 0.0
T_camera_lidar:
  R_row_major:
  - 0.0
  - -1.0
  - 0.0
  - -0.15643446504023087
  - 0.0
  - -0.9876883405951378
  - 0.9876883405951378
  - 0.0
  - -0.15643446504023087
  t_xyz:
  - 0.0
  - 0.07246633182433816
  - 0.11778637761611024
scan_filter:
  min_range_m: 0.3
  max_range_m: 4.0
  angle_min_deg: -70.0
  angle_max_deg: 70.0
